### PR TITLE
Automatic browser refresh

### PR DESCRIPTION
**Pull request by worldeditor11**
After running `pipenv run flask run`
Create another cmd instance and run:
`npm run gulp watch`

Then navigate to http://localhost:5001/
Requires browsersync package.

### CODE REVIEW

**Comment by DangerOnTheRanger** [comment]
Looks pretty good to me - the one change I'd make would be not committing the `static` directory, since that's supposed to be built by Gulp and not be in the repo itself.

**Comment by worldeditor11** [comment]
I think I can add the static folder to gitIgnore. Anyway, this PR is a bust. Changing template html seems to not work at all. Fixing it right now.

**Comment by DangerOnTheRanger** [comment]
I think the `static` folder is still in `.gitignore`, but the folder itself is still in the repo. Also, thanks for fixing `package.json` too - I was wondering what was going on with the failed build.

**Comment by worldeditor11** [comment]
Done.

**Comment by DangerOnTheRanger** [comment]
Alright, everything looks good - thanks again!

**Pull request merged**
